### ISSUE TITLE
Free payment method rejected on a Zero Subtotal Checkout.

### ISSUE THREAD

**Issue by MoooreChristiaan** [buckaroo-it/Magento2#494]
Hi,

We're currently experiencing difficulties when trying to place a zero subtotal quote through our checkout.

The free payment method is checked if it is valid like any regular payment method during the checkout steps. However it is deemed invalid due to the order having a total of 0. The `isAvailableBasedOnAmount()` function of `Model/Method/AbstractMethod.php` contains a check if the total is lower than 0.01 to return a false.
https://github.com/buckaroo-it/Magento2/blob/eb7ae5d99f83d2123a6f9c5fee27ca10ae9a1a95/Model/Method/AbstractMethod.php#L510-L514

However this issue only occurs when the customer is logged in, the guest checkout completely bypasses this check, which is a workaround for now. but we'd rather fix this issue we're experiencing.

Is it an intended error or an oversight in testing? We do have a slightly customized checkout but i'd like to confirm if this is a known bug before deep-diving into it.

Magento version: 2.4.3-p2
Module version: 1.40.0

**Comment by Buckaroo-Rens** [comment]
Thanks @MoooreChristiaan for logging this. We will look into this a.s.a.p.

**Comment by LucianTuriacArnia** [comment]
Sorry for the late reply. We have looked into the issue you're experiencing but we are unable to reproduce it on our end. Here are our technical findings:

1. It is true that the function **isAvailableBasedOnAmount()** is called when the free payment method is checked, but it is called by our observer **Observer/PaymentMethodAvailable.php:61** that will hide all the methods if it is active. Can you please let us know if Point of Sale is enabled for you?

3. We are unable to reproduce the issue you mentioned on our test environment, with and without Point of Sale enabled.
https://www.awesomescreenshot.com/video/17297493?key=8ac27814c8dc9e5543fed825943d53b1

5. Buckaroo doesn't accept payment requests with a 0.00 amount; only 0.01 is accepted as the minimum amount. This is why that condition exists in the code.

6. If Point of Sale (POS) is not active, the free payment method should not be affected, as the free payment method uses the **Magento\Payment\Model\Method\Free** model, which has its own **isAvailable(**) function.

Since we cannot reproduce the issue on our end, it might be worthwhile to investigate your slightly customized checkout to see if it is causing any conflicts. If you have any further questions or need assistance, please feel free to reach out to us.
