### ISSUE TITLE
BP-2867 Fatal Error: with OneStepCheckout in GuestSaveManager.php

### ISSUE THREAD

**Issue by jrswgtr** [buckaroo-it/Magento2#758]
When wanting to place an order as a guest the POST to /rest/{storeview}/V1/guest-carts/{cartUid}/payment-information returns a 500 error with the following message. Can you please look into this?

>  Fatal Error: 'Type of Buckaroo\\Magento2\\Plugin\\GuestSaveManager::$dataManager must not be defined (as in class Onestepcheckout\\Iosc\\Plugin\\GuestSaveManager)' in '/data/web/magento2_wijnspijs/vendor/buckaroo/magento2/Plugin/GuestSaveManager.php' on line 28", trace: "Trace is not available." }

Magento 2.4.6
PHP 8.1.18
Buckaroo/Magento2 v1.45.1
OnestepCheckout/Iosc 1.2.060

**Comment by jrswgtr** [comment]
Can someone please look into this issue? Because this we are unable to upgrade to Magento 2.4.6.

**Comment by Buckaroo-Rene** [comment]
@jrswgtr ,
Unfortunately it is not reproducible for us at our own staging
If possible, could we get temporary access to a staging environment where this issue is happening?
That would speed up things and hopefully we can find a solution for you.

Please contact [support@buckaroo.nl](mailto:support@buckaroo.nl) to the attention of Sander if this is possible. Then we can sort things out and send a IP address for one of our developers who is going to pick this up,

**Comment by jrswgtr** [comment]
@Buckaroo-Rene thanks for your reply, I sent a mail to Sander with more details and the request for an SSH public key.

**Comment by Buckaroo-Rene** [comment]
> @Buckaroo-Rene thanks for your reply, I sent a mail to Sander with more details and the request for an SSH public key.

Thanks, we've got the message from Sander. He'll send the neccesary information to you.
We'll pick it up from there.

**Comment by Buckaroo-Rene** [comment]
@jrswgtr Great, thanks for the confirmation.
We have scheduled the new release (1.46.0) for tomorrow morning.
So I'll close this issue for now.
